apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  ports:
  - port: 80               # Port exposed externally
    targetPort: 80         # Port exposed internally by the app
  selector:
    app: netflix-app       # Must match the labels of your Deployment pods
